package main

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

func searchReferences(ctx context.Context, args searchArgs) ([]referenceItem, error) {
	query := args.Query
	switch args.Platform {
	case "web":
		query += " browser game web ui"
	case "mobile-web":
		query += " mobile web game ui touch"
	case "both":
		query += " browser game ui mobile web"
	}

	htmlBody, err := fetchDuckDuckGoHTML(ctx, query, args.Language)
	if err != nil {
		return nil, err
	}

	raw := parseDuckDuckGoResults(htmlBody)
	if len(raw) == 0 {
		return nil, errNoReferences
	}

	uniq := map[string]referenceItem{}
	for _, item := range raw {
		if _, ok := uniq[item.URL]; ok {
			continue
		}
		if len(uniq) >= args.Limit {
			break
		}
		item.PlatformTag = args.Platform
		uniq[item.URL] = item
	}

	results := make([]referenceItem, 0, len(uniq))
	for _, it := range uniq {
		results = append(results, it)
	}
	sort.SliceStable(results, func(i, j int) bool {
		return results[i].Title < results[j].Title
	})

	if args.IncludeImages {
		for i := range results {
			if og := fetchOGImage(ctx, results[i].URL); og != "" {
				results[i].OGImage = og
			}
		}
	}

	return results, nil
}

func buildBenchmark(ctx context.Context, args benchmarkArgs) ([]benchmarkItem, error) {
	rows := make([]benchmarkItem, 0, len(args.URLs))
	for _, u := range args.URLs {
		meta := fetchPageMeta(ctx, u)
		row := benchmarkItem{
			URL:                  u,
			Title:                meta.Title,
			Description:          meta.Description,
			OGImage:              meta.OGImage,
			CoreLoopGuess:        inferCoreLoop(meta.Title, meta.Description),
			FTUEComplexity:       inferFTUE(meta.Description),
			InteractionDensity:   inferDensity(meta.Description),
			MobileTouchReadiness: inferMobile(meta.Description),
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func scoreReferences(args scoreArgs) []scoredReference {
	nowUTC := time.Now().UTC().Format(time.RFC3339)
	rows := make([]scoredReference, 0, len(args.Items))

	for _, it := range args.Items {
		text := strings.ToLower(it.Title + " " + it.Snippet)
		hook := scoreHook(text)
		interaction := scoreInteraction(text)
		mobile := scoreMobile(text, it.PlatformTag)
		monetization := scoreMonetization(text)
		novelty := scoreNovelty(text)

		total := int(
			float64(hook)*args.Weights.Hook +
				float64(interaction)*args.Weights.Interaction +
				float64(mobile)*args.Weights.Mobile +
				float64(monetization)*args.Weights.Monetization +
				float64(novelty)*args.Weights.Novelty,
		)

		why := make([]string, 0, 5)
		if hook >= 70 {
			why = append(why, "Strong first-session hook signals")
		}
		if interaction >= 70 {
			why = append(why, "High interaction/decision density signals")
		}
		if mobile >= 70 {
			why = append(why, "Mobile-touch readiness signal is strong")
		}
		if monetization >= 70 {
			why = append(why, "Monetization loop keyword coverage is strong")
		}
		if novelty >= 70 {
			why = append(why, "Novel mechanic vocabulary detected")
		}
		if len(why) == 0 {
			why = append(why, "Balanced baseline reference; requires manual visual confirmation")
		}

		rows = append(rows, scoredReference{
			Title:          it.Title,
			URL:            it.URL,
			Domain:         it.Domain,
			PlatformTag:    it.PlatformTag,
			OGImage:        it.OGImage,
			CompositeScore: clampScore(total),
			ScoreBreakdown: map[string]int{
				"hook":         hook,
				"interaction":  interaction,
				"mobile":       mobile,
				"monetization": monetization,
				"novelty":      novelty,
			},
			Why: why,
			Provenance: scoreProvenance{
				SourceURL:      it.URL,
				AnalyzedAtUTC:  nowUTC,
				ReferenceNotes: "Heuristic score generated by webgame-reference-mcp.",
			},
			RecommendedForStep: map[string]bool{
				"ftue_0_60s":          hook >= 60 && mobile >= 60,
				"session_loop_depth":  interaction >= 65 && novelty >= 55,
				"light_spend_testing": monetization >= 60,
			},
		})
	}

	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].CompositeScore == rows[j].CompositeScore {
			return rows[i].Title < rows[j].Title
		}
		return rows[i].CompositeScore > rows[j].CompositeScore
	})

	return rows
}

func visionReviewImages(ctx context.Context, args visionReviewArgs) ([]visionReviewRow, error) {
	apiKey := strings.TrimSpace(os.Getenv("OPENAI_API_KEY"))
	if apiKey == "" {
		return nil, errors.New("OPENAI_API_KEY is required for vision review tool")
	}

	rows := make([]visionReviewRow, 0, len(args.ImageURLs))
	for _, imageURL := range args.ImageURLs {
		row, err := requestVisionReview(ctx, apiKey, args.Model, imageURL, args.Context)
		if err != nil {
			return nil, fmt.Errorf("vision review failed for %s: %w", imageURL, err)
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func auditModelPolicyDrift(args modelPolicyAuditArgs) ([]modelPolicyViolation, error) {
	violations := make([]modelPolicyViolation, 0)
	allowedExt := map[string]bool{
		".md": true, ".go": true, ".ts": true, ".js": true, ".json": true, ".yaml": true, ".yml": true,
	}
	skipDir := map[string]bool{
		".git": true, "node_modules": true, "target": true, "dist": true, "out": true,
	}

	err := filepath.WalkDir(args.RootPath, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if skipDir[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !allowedExt[strings.ToLower(filepath.Ext(path))] {
			return nil
		}

		file, err := os.Open(path)
		if err != nil {
			return nil
		}
		defer file.Close()

		scanner := bufio.NewScanner(file)
		lineNo := 0
		for scanner.Scan() {
			lineNo++
			line := scanner.Text()
			for _, model := range args.ForbiddenModels {
				if strings.Contains(line, model) {
					violations = append(violations, modelPolicyViolation{
						FilePath: path,
						Line:     lineNo,
						Model:    model,
						Excerpt:  strings.TrimSpace(line),
					})
				}
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.SliceStable(violations, func(i, j int) bool {
		if violations[i].FilePath == violations[j].FilePath {
			return violations[i].Line < violations[j].Line
		}
		return violations[i].FilePath < violations[j].FilePath
	})

	return violations, nil
}

func inferCoreLoop(title, desc string) string {
	text := strings.ToLower(title + " " + desc)
	switch {
	case strings.Contains(text, "idle"):
		return "Idle progression loop"
	case strings.Contains(text, "card"):
		return "Card-choice loop"
	case strings.Contains(text, "strategy"):
		return "Strategic decision loop"
	default:
		return "Short session decision loop"
	}
}

func inferFTUE(desc string) string {
	text := strings.ToLower(desc)
	switch {
	case strings.Contains(text, "tutorial") || strings.Contains(text, "guide"):
		return "Guided"
	case strings.Contains(text, "simple") || strings.Contains(text, "quick"):
		return "Lightweight"
	default:
		return "Unknown"
	}
}

func inferDensity(desc string) string {
	text := strings.ToLower(desc)
	switch {
	case strings.Contains(text, "fast") || strings.Contains(text, "real-time"):
		return "High"
	case strings.Contains(text, "turn") || strings.Contains(text, "choice"):
		return "Medium"
	default:
		return "Low to medium"
	}
}

func inferMobile(desc string) string {
	text := strings.ToLower(desc)
	if strings.Contains(text, "mobile") || strings.Contains(text, "touch") {
		return "Likely optimized"
	}
	return "Needs manual check"
}

func scoreHook(text string) int {
	score := 45
	score += keywordHits(text, []string{"tutorial", "onboarding", "quick", "instant", "tap", "one-click", "first minute"}) * 8
	score += keywordHits(text, []string{"choice", "decision", "consequence"}) * 6
	return clampScore(score)
}

func scoreInteraction(text string) int {
	score := 40
	score += keywordHits(text, []string{"strategy", "turn-based", "real-time", "deck", "combat", "builder", "simulation"}) * 7
	score += keywordHits(text, []string{"multiplayer", "pvp", "raid", "boss", "guild"}) * 6
	return clampScore(score)
}

func scoreMobile(text, platform string) int {
	score := 38
	if platform == "mobile-web" || platform == "both" {
		score += 10
	}
	score += keywordHits(text, []string{"mobile", "touch", "tap", "swipe", "portrait", "responsive", "pwa"}) * 8
	return clampScore(score)
}

func scoreMonetization(text string) int {
	score := 32
	score += keywordHits(text, []string{"battle pass", "season", "shop", "skin", "cosmetic", "event pass", "bundle"}) * 9
	score += keywordHits(text, []string{"gacha", "summon", "crate", "premium", "subscription"}) * 7
	return clampScore(score)
}

func scoreNovelty(text string) int {
	score := 35
	score += keywordHits(text, []string{"roguelike", "asymmetric", "sandbox", "god game", "emergent", "procedural"}) * 9
	score += keywordHits(text, []string{"narrative", "branching", "meta-progression"}) * 6
	return clampScore(score)
}

func keywordHits(text string, keys []string) int {
	hits := 0
	for _, key := range keys {
		if strings.Contains(text, key) {
			hits++
		}
	}
	return hits
}

func clampScore(v int) int {
	if v < 0 {
		return 0
	}
	if v > 100 {
		return 100
	}
	return v
}

func auditMarketLaunchReadiness(args marketLaunchAuditArgs) (marketLaunchAuditReport, error) {
	root := strings.TrimSpace(args.ProjectRoot)
	if root == "" {
		root = "."
	}

	criteria := make([]marketLaunchCriterion, 0, 7)
	blockers := make([]string, 0, 6)

	backendIndex := filepath.Join(root, "apps", "backend", "src", "index.ts")
	frontendMain := filepath.Join(root, "apps", "frontend", "src", "main.ts")
	frontendStyle := filepath.Join(root, "apps", "frontend", "src", "style.css")

	backendContent := mustReadFile(backendIndex)
	frontendContent := mustReadFile(frontendMain)
	styleContent := mustReadFile(frontendStyle)

	// 1) Playable core loop
	loopReady := containsAll(frontendContent, []string{"/api/grant", "/api/divine-react", "Epoch", "season"})
	criteria = append(criteria, criterionFromBool(
		"core_loop",
		"Playable Core Loop",
		loopReady,
		88,
		42,
		"Grant -> Behavior -> Divine reaction loop is wired in frontend.",
		"No playable retention baseline means immediate bounce.",
		"Require single-session loop completion rate >= 35%.",
	))
	if !loopReady {
		blockers = append(blockers, "Core loop wiring is incomplete.")
	}

	// 2) Monetization surface
	monetizationHits := keywordCount(frontendContent+"\n"+backendContent, []string{
		"shop", "bundle", "premium", "battle pass", "purchase", "iap", "subscription", "price",
	})
	monetizationReady := monetizationHits >= 3
	criteria = append(criteria, criterionFromBool(
		"monetization_surface",
		"Monetization Surface",
		monetizationReady,
		78,
		25,
		fmt.Sprintf("Detected %d monetization-related keywords in operational code.", monetizationHits),
		"No monetization surface means zero conversion path.",
		"Add one low-friction entry SKU and one cosmetic-only offer.",
	))
	if !monetizationReady {
		blockers = append(blockers, "Monetization surface is missing or too weak.")
	}

	// 3) Event instrumentation
	analyticsHits := keywordCount(frontendContent+"\n"+backendContent, []string{
		"analytics", "track", "event", "amplitude", "posthog", "mixpanel", "gtag",
	})
	analyticsReady := analyticsHits >= 2
	criteria = append(criteria, criterionFromBool(
		"analytics",
		"Analytics Instrumentation",
		analyticsReady,
		82,
		20,
		fmt.Sprintf("Detected %d analytics/event keywords.", analyticsHits),
		"Without telemetry, retention and funnel tuning is blind.",
		"Track FTUE completion, first reaction, and day-1 return intent.",
	))
	if !analyticsReady {
		blockers = append(blockers, "Analytics instrumentation is insufficient.")
	}

	// 4) UX readability baseline
	readabilityReady := strings.Contains(styleContent, "@media") && strings.Contains(styleContent, ".cta")
	readabilityEvidence := "Responsive rule and CTA style are present."
	if !readabilityReady {
		readabilityEvidence = "Responsive and CTA style signatures are incomplete in style layer."
	}
	criteria = append(criteria, criterionFromBool(
		"ux_readability",
		"Mobile/PC Readability Baseline",
		readabilityReady,
		80,
		45,
		readabilityEvidence,
		"Unreadable first screen kills 1-2 second hook.",
		"Verify above-the-fold hook on 390x844 and 1440x900.",
	))
	if !readabilityReady {
		blockers = append(blockers, "Readability baseline for responsive UI is missing.")
	}

	// 5) Safety fallback
	fallbackReady := containsAll(backendContent, []string{"fallback", "checkSessionRateLimit", "checkDailyCap"})
	criteria = append(criteria, criterionFromBool(
		"safety_fallback",
		"Safety and Cost Fallback",
		fallbackReady,
		84,
		30,
		"Rate limit and deterministic fallback paths are present.",
		"Provider failure without fallback breaks trust and sessions.",
		"Keep degraded mode playable under provider outage.",
	))
	if !fallbackReady {
		blockers = append(blockers, "Fallback/safety path is incomplete.")
	}

	// 6) Launch trust pages
	trustReady := fileExists(filepath.Join(root, "apps", "frontend", "public", "privacy.html")) ||
		fileExists(filepath.Join(root, "apps", "frontend", "public", "terms.html"))
	criteria = append(criteria, criterionFromBool(
		"trust_policy",
		"Privacy/Terms Launch Readiness",
		trustReady,
		70,
		10,
		"Privacy/terms static page presence check.",
		"Missing trust pages can block store/payment review.",
		"Add privacy + terms with data/use policy before paid rollout.",
	))
	if !trustReady {
		blockers = append(blockers, "Privacy/Terms launch pages are missing.")
	}

	// 7) AI model policy
	modelPolicyReady := regexp.MustCompile(`gpt-5-nano`).MatchString(backendContent)
	criteria = append(criteria, criterionFromBool(
		"model_policy",
		"Model Cost Baseline Policy",
		modelPolicyReady,
		72,
		35,
		"Backend baseline model check.",
		"Unbounded model choice can burn margin before PMF.",
		"Default nano tier, explicit escalation only for flagged tasks.",
	))

	total := 0
	for _, c := range criteria {
		total += c.Score
	}
	overall := total / len(criteria)

	decision := "NO_GO"
	if len(blockers) == 0 && overall >= 75 {
		decision = "GO"
	} else if len(blockers) <= 2 && overall >= 60 {
		decision = "GO_WITH_GATES"
	}

	return marketLaunchAuditReport{
		ProjectRoot:     root,
		GeneratedAtUTC:  time.Now().UTC().Format(time.RFC3339),
		OverallScore:    clampScore(overall),
		LaunchDecision:  decision,
		Criteria:        criteria,
		CriticalBlocker: blockers,
	}, nil
}

func criterionFromBool(key, title string, ok bool, passScore, failScore int, evidence, impact, nextCheck string) marketLaunchCriterion {
	status := "pass"
	score := passScore
	if !ok {
		status = "fail"
		score = failScore
	}
	return marketLaunchCriterion{
		Key:       key,
		Title:     title,
		Status:    status,
		Score:     score,
		Evidence:  evidence,
		Impact:    impact,
		NextCheck: nextCheck,
	}
}

func containsAll(text string, needles []string) bool {
	lower := strings.ToLower(text)
	for _, n := range needles {
		if !strings.Contains(lower, strings.ToLower(n)) {
			return false
		}
	}
	return true
}

func keywordCount(text string, keywords []string) int {
	lower := strings.ToLower(text)
	count := 0
	for _, k := range keywords {
		if strings.Contains(lower, strings.ToLower(k)) {
			count++
		}
	}
	return count
}

func mustReadFile(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(b)
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return !info.IsDir()
}
