name: "reusable: auto merge"

on:
  workflow_call:
    inputs:
      merge_method:
        description: merge strategy (merge|squash|rebase)
        required: false
        default: squash
        type: string

permissions: read-all

jobs:
  auto-approve-and-enable:
    if: >
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto approve PR
        id: auto_approve
        continue-on-error: true
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.auto_approve.outcome == 'success'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: ${{ inputs.merge_method }}
